### ISSUE TITLE
Changelog for versions

### ISSUE THREAD

**Issue by kyeshmz** [ceifa/steamworks.js#162]
Is there an active changelog for what each new version brings? I tried to figure out through npm, but it doesn't seem like there was one.

**Comment by ceifa** [comment]
No :/
If you really need that you can see the commits to the "version" on package.json and see the commits between them.
Dupp of https://github.com/ceifa/steamworks.js/issues/39

**Comment by kyeshmz** [comment]
@ceifa can you help me understand how you do releases? If its just all manual, I can automate it, or help use some of the automation tools that github already has

**Comment by kyeshmz** [comment]
Is it possible to add a release action after your publishing? @ceifa
then we could start generating from tags to tags

```
 - name: Publish to npm
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: Release v${{ steps.publish.outputs.version }}
                  tag_name: v${{ steps.publish.outputs.version }}
                  generate_release_notes: true
                  draft: false
```
