### ISSUE TITLE
Tag releases in Github

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#39]
It would be nice if the Github release automation would tag a release, linking to a commit, etc.

**Comment by ceifa** [comment]
I like it and how https://github.com/napi-rs/napi-rs was doing it. But tbh idk how it works

**Comment by ceifa** [comment]
https://keepachangelog.com/en/1.0.0/

**Comment by kyeshmz** [comment]
Just incase its not evident in the other issue,

Is it possible to add a release action after your publishing? @ceifa
then we could start generating from tags to tags

also it seems not possible to pr github action workflows

```
 - name: Publish to npm
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: Release v${{ steps.publish.outputs.version }}
                  tag_name: v${{ steps.publish.outputs.version }}
                  generate_release_notes: true
                  draft: false
```
